In [1]:
## CS 207 - Group 9
## Demo for Project checkpoint 1
## Reaction rate calculator

from chemkin import *

reader = xml2dict()
file_path = input('Welcome to the Reaction Rate calculator. Input a valid xml file.')
reader.parse(file_path)
info = reader.get_info()

reactions = [Reaction(**r) for r in info[1]]
species=info[0]
rs = ReactionSystem(reactions,species_ls= species)

str_of_concs = input('input concentrations, separated by commas, in the following order: '+str(species))
array_of_concs = [float(i) for i in str_of_concs.split(',')]
concs = dict(zip(species,array_of_concs))
print(concs)
rs.set_concs(concs)

temp_string = input('input non-negative temperature in Kelvins.')
rs.set_temp(float(temp_string))

rs.get_reac_rate()
print('Reaction rate for species ',species,'at temperature', temp_string, 'with concentrations', array_of_concs,'is, in order:')
print(rs.get_reac_rate())

print('Progress rate for reactions at temperature', temp_string, 'with concentrations', array_of_concs,'is:')
print(rs.get_progress_rate())


Welcome to the Reaction Rate calculator. Input a valid xml file.rxns2.xml
input concentrations, separated by commas, in the following order: ['H2', 'O2', 'OH', 'HO2', 'H2O']2,1,0.5,1,1
{'H2': 2.0, 'O2': 1.0, 'OH': 0.5, 'HO2': 1.0, 'H2O': 1.0}
input non-negative temperature in Kelvins.750
nu_react [[ 2.  0.  0.]
 [ 1.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
nu_prod [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 2.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
nu [[-1.  0.  0.]
 [-1.  1. -1.]
 [ 2. -1.  1.]
 [ 0. -1.  1.]
 [ 0.  1. -1.]]
Reaction rate for species  ['H2', 'O2', 'OH', 'HO2', 'H2O'] at temperature 750 with concentrations [2.0, 1.0, 0.5, 1.0, 1.0] is, in order:
nu_react [[ 2.  0.  0.]
 [ 1.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
nu_prod [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 2.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]]
nu [[-1.  0.  0.]
 [-1.  1. -1.]
 [ 2. -1.  1.]
 [ 0. -1.  1.]
 [ 0.  1. -1.]]
[-3607077.87280406 -5613545.18362079  9220623.05642485  2006467.31081673
 -2

In [ ]:
[-3607077.87280407 -5613545.1836208   9220623.05642486  2006467.31081673
 -2006467.31081673]
[ -2.81117621e+08  -2.85597559e+08   5.66715180e+08   4.47993847e+06
  -4.47993847e+06]
[ -1.80426143e+09  -1.81043736e+09   3.61469878e+09   6.17593098e+06
  -6.17593098e+06]
concs = np.array([2.0, 1.0, 0.5, 1.0, 1.0])
Temps = [750.0, 1500.0, 2500.0]
