In [1]:
import numpy as np

import CoeffLaw
from Reaction import Reaction
from ReactionSystem import ReactionSystem

import sqlite3
from xml2dict import xml2dict
from database_query import CoeffQuery

In [2]:
reader = xml2dict()
reader.parse('rxns_reversible.xml')
info = reader.get_info()

nasa_query = CoeffQuery('nasa_thermo.sqlite')

In [3]:
species = info[0]
reactions = [Reaction(**r) for r in info[1]]
print(reactions[0])

Reaction Equation:
1H + 1O2 [=] 1O + 1OH
----------------------------------------
Reaction Info:
ID: reaction01
TYPE: Elementary
reversible: True
coeffLaw: modifiedArrhenius
coeffParams: [('A', 3547000000000000.0), ('E', 16599.0), ('R', 8.314), ('b', -0.406)]
coeffUnits: []


In [4]:
T = 1500
concs = dict(
    H=2, O=1, OH=0.5, H2=1,
    H2O=1, O2=1, HO2=0.5, H2O2=1)
reaction_sys = ReactionSystem(
    reactions, species, nasa_query, 
    initial_T=T, initial_concs=concs)

ke = CoeffLaw.BackwardLaw().equilibrium_coeffs(
    reaction_sys.get_nu_2() - reaction_sys.get_nu_1(), 
    reaction_sys.get_a(), T)
ke

array([  6.11555529e-02,   1.15378232e+00,   3.50371252e+01,
         3.29302792e-02,   3.93625529e+07,   2.77742942e+06,
         4.54158174e+07,   1.37915069e+09,   7.21140169e+10,
         7.41051158e+02,   8.55011722e+02])

In [5]:
kf, kb = reaction_sys.get_reac_rate_coefs()
ke = kf / kb
ke

array([  6.11555529e-02,   1.15378232e+00,   3.50371252e+01,
         3.29302792e-02,   3.93625529e+07,   2.77742942e+06,
         4.54158174e+07,   1.37915069e+09,   7.21140169e+10,
         7.41051158e+02,   8.55011722e+02])

In [6]:
reaction_sys.get_a()

array([[  2.50000001e+00,  -2.30842973e-11,   1.61561948e-14,
         -4.73515235e-18,   4.98197357e-22,   2.54736599e+04,
         -4.46682914e-01],
       [  2.56942078e+00,  -8.59741137e-05,   4.19484589e-08,
         -1.00177799e-11,   1.22833691e-15,   2.92175791e+04,
          4.78433864e+00],
       [  3.09288767e+00,   5.48429716e-04,   1.26505228e-07,
         -8.79461556e-11,   1.17412376e-14,   3.85865700e+03,
          4.47669610e+00],
       [  3.33727920e+00,  -4.94024731e-05,   4.99456778e-07,
         -1.79566394e-10,   2.00255376e-14,  -9.50158922e+02,
         -3.20502331e+00],
       [  3.03399249e+00,   2.17691804e-03,  -1.64072518e-07,
         -9.70419870e-11,   1.68200992e-14,  -3.00042971e+04,
          4.96677010e+00],
       [  3.28253784e+00,   1.48308754e-03,  -7.57966669e-07,
          2.09470555e-10,  -2.16717794e-14,  -1.08845772e+03,
          5.45323129e+00],
       [  4.01721090e+00,   2.23982013e-03,  -6.33658150e-07,
          1.14246370e-10,  -1.07

In [7]:
reaction_sys.get_reac_rate()

array([  1.32279655e+14,  -3.12877268e+14,  -1.37621783e+14,
         6.07049182e+13,   6.45299057e+13,   3.36486899e+14,
        -4.18771320e+13,  -1.01625194e+14])

In [10]:
T = 3000
concs = dict(
    H=2, O=1, OH=0.5, H2=1,
    H2O=1, O2=1, HO2=0.5, H2O2=1)
reaction_sys = ReactionSystem(
    reactions, species, nasa_query, 
    initial_T=T, initial_concs=concs)

kf, kb = reaction_sys.get_reac_rate_coefs()
ke = kf / kb
ke

array([  8.37240608e-01,   1.63324159e+00,   3.01623159e+00,
         5.41484147e-01,   3.09491259e+03,   4.23203356e+03,
         5.05473996e+03,   9.33497312e+03,   4.24377782e+05,
         3.32459580e+01,   5.42986813e+01])

In [11]:
reaction_sys.get_reac_rate()

array([ -2.71830749e+14,  -2.93961040e+13,   4.16606388e+14,
         6.16549019e+13,   3.31414094e+13,  -5.94443978e+13,
         3.29053644e+13,  -1.83636813e+14])

In [8]:
reaction_sys.get_progress_rate()

array([ -2.95046638e+14,   1.42111693e+12,   4.55499295e+12,
        -1.73976060e+13,   1.55399358e+13,   6.91352053e+13,
         1.62499996e+13,   7.51873184e+12,   3.50592007e+13,
         5.09434918e+13,   1.56247770e+13])