In [1]:
import numpy as np
from copy import deepcopy

from useful_structure import PartialLockedDict
from mathematical_science import MathModel
from check_and_response import ValueCheck

import CoeffLaw
from Reaction import Reaction
from xml2dict import xml2dict 

import sqlite3
from database_query import *

In [2]:
nasa_query = CoeffQuery('nasa_thermo.sqlite')

In [3]:
from ReactionSystem import *

In [4]:
reactions = [ Reaction(reversible='yes', reactants={'H2':2,'O2':1}, products={'OH':2,'H2':1}) ]
species = [ 'H2', 'O2', 'OH' ]
rs = ReactionSystem(reactions, species, nasa_query, 2200)

In [5]:
a = rs.get_a()
a

array([[  2.34433112e+00,   7.98052075e-03,  -1.94781510e-05,
          2.01572094e-08,  -7.37611761e-12,  -9.17935173e+02,
          6.83010238e-01],
       [  3.78245636e+00,  -2.99673416e-03,   9.84730201e-06,
         -9.68129509e-09,   3.24372837e-12,  -1.06394356e+03,
          3.65767573e+00],
       [  3.99201543e+00,  -2.40131752e-03,   4.61793841e-06,
         -3.88113333e-09,   1.36411470e-12,   3.61508056e+03,
         -1.03925458e-01]])

In [6]:
nu = rs.get_nu_2() - rs.get_nu_1()
nu

array([[-1.],
       [-1.],
       [ 2.]])

In [7]:
ke = BackwardLaw().equilibrium_coeffs(nu, a, 2200)
ke

array([ 1.00714881])

In [10]:
concs = dict(H2=2, O2=2, OH=2*np.sqrt(ke))
rs.set_concs(concs)

In [14]:
rs.get_reac_rate()

array([ -1.77635684e-15,  -1.77635684e-15,   3.55271368e-15])

In [11]:
rs._a

array([[  2.34433112e+00,   7.98052075e-03,  -1.94781510e-05,
          2.01572094e-08,  -7.37611761e-12,  -9.17935173e+02,
          6.83010238e-01],
       [  3.78245636e+00,  -2.99673416e-03,   9.84730201e-06,
         -9.68129509e-09,   3.24372837e-12,  -1.06394356e+03,
          3.65767573e+00],
       [  3.99201543e+00,  -2.40131752e-03,   4.61793841e-06,
         -3.88113333e-09,   1.36411470e-12,   3.61508056e+03,
         -1.03925458e-01]])

In [12]:
rs.get_reac_rate_coefs()

(array([ 1.]), array([ 0.99290193]))